### ISSUE TITLE
compatibility @vuejs/composition-api

### ISSUE THREAD

**Issue by Dekhnar** [beizhedenglong/vue-hooks-form#2]
Hello,

Is it possible to have a version compatible with https://github.com/vuejs/composition-api for an integration with https://github.com/nuxt-community/composition-api ?

**Comment by beizhedenglong** [comment]
It's possible to work with Vue 2.x by using https://github.com/vuejs/composition-api, But it needs some extra work. Do you want to implement it?

**Comment by singha-cto** [comment]
On nuxt project cannot use function `useForm`
it occur `TypeError: vue.ref is not a function`

**Comment by beizhedenglong** [comment]
@singha-cto Can you provide a demo repo?

**Comment by sabuydee** [comment]
@beizhedenglong For error case above comment of @singha-cto 
Repo: https://github.com/sabuydee/vue-hooks-form-test

**Comment by EastSun5566** [comment]
Hello @beizhedenglong, thank you for the library. I really like this API and would like to integrate it into my company's Nuxt2 project. To implement the cross-Vue 2 support feature, I plan to use [Vue Demi](https://github.com/vueuse/vue-demi). I will be submitting a pull request shortly.

**Comment by beizhedenglong** [comment]
@EastSun5566 Your fix has been released https://www.npmjs.com/package/vue-hooks-form?activeTab=versions.
