### ISSUE TITLE
Misc. TypeScript/Dpcumentation issues

### ISSUE THREAD

**Issue by devlsh** [beizhedenglong/vue-hooks-form#3]
I've been using the library and love it (Great job!)

However there are a couple issues I've found with using TypeScript (Especially with Volar for VSCode, since now `<template>` syntax is included in type checking):

### `field.ref` typing incorrect for use-case(?)

Error:

![](https://i.imgur.com/lDoU2vQ.png)

Vue 3 is expecting the following type for `:ref` bindings:

```typescript
declare type VNodeRef = string | Ref | ((ref: object | null, refs: Record<string, any>) => void);
```

### Error binding example incorrect(?)

Given the documentation for error handling:

```vue
<p v-if="password.error">{{ password.error.message }}</p>
```

This is erroring, since the `error` property is an `Array` - not sure if the typings are wrong, or the intended functionality

**Comment by beizhedenglong** [comment]
Do you want to fix these issues?

**Comment by beizhedenglong** [comment]
password.error is `undefined` or object, can you give me an example that indicate it an array? 
by the way you can use `!!` to force  it into boolean 
```js
<p v-if="!!password.error">{{ password.error.message }}</p>
```
