### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by shlroland** [beizhedenglong/vue-hooks-form#4]
I love the react hook form and Vue3 , so I find this similar library for Vue3. But it had not been updated since January 2021.If this library will be maintained, I want to contribute my effort. @beizhedenglong

**Comment by beizhedenglong** [comment]
Hi @shlroland, Thanks for your interest. This project will be maintained, but I'm very busy with work recently. If you want to contribute to this project, PR is welcome. I will review your PR in time.

**Comment by shlroland** [comment]
> Hi @shlroland, Thanks for your interest. This project will be maintained, but I'm very busy with work recently. If you want to contribute to this project, PR is welcome. I will review your PR in time.

could I get your wechat ID to have a discuss about roadmap?

**Comment by beizhedenglong** [comment]
My WeChat: Problem_of_eval
